### ISSUE TITLE
Failing Test

### ISSUE THREAD

**Issue by PhaneendraNakkala** [neo4j-examples/movies-java-spring-data-neo4j#14]
Hi,
 I cloned the master. Following unit tests are failing. Is it a known issue?
MovieRepositoryTest
`testFindByTitle`
`testFindByTitleContaining`

-Phaneendra

**Comment by straumat** [comment]
Same here  : 
`testFindByTitle(movies.spring.data.neo4j.repositories.MovieRepositoryTest)  Time elapsed: 0.421 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at movies.spring.data.neo4j.repositories.MovieRepositoryTest.testFindByTitle(MovieRepositoryTest.java:72)

testFindByTitleContaining(movies.spring.data.neo4j.repositories.MovieRepositoryTest)  Time elapsed: 0.457 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at movies.spring.data.neo4j.repositories.MovieRepositoryTest.testFindByTitleContaining(MovieRepositoryTest.java:84)`

**Comment by PhaneendraNakkala** [comment]
I've fixed the failing tests. Please check the pull request.
@mangrish may be?

Cheers!
